SQLITE_BD_FILE_PATH = 'data/reports.db'
REPORTS_META_DATA_TABLE_NAME = 'REPORTS_META_DATA'

REPORTS_META_DATA_TABLE_CREATION_QUERY = f"""
    CREATE TABLE {REPORTS_META_DATA_TABLE_NAME} (
            ID INTEGER PRIMARY KEY,
            ENUM TEXT NOT NULL,
            COMPANY TEXT NOT NULL,
            COMPETITOR TEXT NOT NULL,
            LOCATION TEXT NOT NULL,
            DURATION TEXT NOT NULL,
            TTL TEXT NOT NULL
        );

"""
